// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9i4BtyJOfiuxcBCZ5778Ak7bXEDGFjc',
    appId: '1:730567782472:web:200ad76c203b8285cde87d',
    messagingSenderId: '730567782472',
    projectId: 'doctor-hunt-86e54',
    authDomain: 'doctor-hunt-86e54.firebaseapp.com',
    storageBucket: 'doctor-hunt-86e54.firebasestorage.app',
    measurementId: 'G-NPYDF8K5VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoo_IQPYoBfMHp7RASfzOOFmss9uPb4HQ',
    appId: '1:730567782472:android:2aec5e412ec83dc2cde87d',
    messagingSenderId: '730567782472',
    projectId: 'doctor-hunt-86e54',
    storageBucket: 'doctor-hunt-86e54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOHKp3g5r_ExeADmbJsGI8jrcHSrS_4KA',
    appId: '1:730567782472:ios:3f4eca227e6715c4cde87d',
    messagingSenderId: '730567782472',
    projectId: 'doctor-hunt-86e54',
    storageBucket: 'doctor-hunt-86e54.firebasestorage.app',
    iosClientId: '730567782472-gcpp9f4a7rndusiqov2t5n3ia0d8rsdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOHKp3g5r_ExeADmbJsGI8jrcHSrS_4KA',
    appId: '1:730567782472:ios:3f4eca227e6715c4cde87d',
    messagingSenderId: '730567782472',
    projectId: 'doctor-hunt-86e54',
    storageBucket: 'doctor-hunt-86e54.firebasestorage.app',
    iosClientId: '730567782472-gcpp9f4a7rndusiqov2t5n3ia0d8rsdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR9i4BtyJOfiuxcBCZ5778Ak7bXEDGFjc',
    appId: '1:730567782472:web:99921a216e349f82cde87d',
    messagingSenderId: '730567782472',
    projectId: 'doctor-hunt-86e54',
    authDomain: 'doctor-hunt-86e54.firebaseapp.com',
    storageBucket: 'doctor-hunt-86e54.firebasestorage.app',
    measurementId: 'G-NJP7XRE2WY',
  );
}
